name: Android Release

on:
  push:
    tags:
      - 'v*'   # например, v0.1.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3

      # (Если уже настроен signingConfig release)
      - name: Assemble Release
        run: ./gradlew --no-daemon clean bundleRelease assembleRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: |
            app/build/outputs/bundle/release/*.aab
            app/build/outputs/apk/release/*.apk
